---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: github
  label: github
  description: Github repo link
  config:
    required: true
- type: text
  name: demo
  label: Demo
  description: Demo url
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/tcg.md
- projects/quizmaster.md
- projects/blog-api.md
- projects/code-snippets.md
- projects/gitgud.md
- projects/carleudd.md
- projects/pwd.md
